language: cpp
dist: bionic
matrix:
  include:
    - name: x86_64-linux-gnu-clang-release
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libstdc++-9-dev', 'clang-9']
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - CMAKE_BUILD_TYPE=RelWithDebInfo
        - COVERAGE=0
        - ANALYSIS=0
    - name: x86_64-linux-gnu-clang-analysis
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libstdc++-9-dev', 'clang-9', 'clang-tools-9']
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - CMAKE_BUILD_TYPE=Debug
        - COVERAGE=0
        - ANALYSIS=1
    - name: x86_64-linux-gnu-gcc-coverage
      os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9']
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - GCOV_BINARY=/usr/bin/gcov-9
        - CMAKE_BUILD_TYPE=Debug
        - CMAKE_PREFIX_PATH="$HOME/.local/usr/local" # gcov location
        - COVERAGE=1
        - ANALYSIS=0
      install:
        - sudo apt-get -y install libperlio-gzip-perl libconfig-json-perl
        - wget https://github.com/linux-test-project/lcov/archive/master.zip -O lcov.zip
        - unzip lcov.zip
        - make -C lcov-master install DESTDIR=$HOME/.local
        - cp $GCOV_BINARY $HOME/.local/usr/local/bin/gcov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - |
    cmake .. \
        -DBUILD_TESTING=1 \
        -DGTA3SC_COVERAGE=$COVERAGE \
        -DGTA3SC_ANALYSIS=$ANALYSIS \
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
  - cmake --build . --target coverage
