language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-6', 'g++-6' ]
    - compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-6', 'g++-6', 'libstdc++6' ]
      env:
        global:
          - LLVM_VERSION=3.8.0
          - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
      before_install:
        - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
        - mkdir $HOME/clang+llvm
        - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
        - export PATH=$HOME/clang+llvm/bin:$PATH
install:
  - sudo pip install lit
  - sudo pip install OutputCheck
script:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-6"; fi
  - if [ "$CXX" == "clang++" ];  then export CXX="clang++"; fi
  - $CXX --version
  - lit --version
  - which OutputCheck
  - mkdir build
  - cd build
  - cmake .. && make
  - cd ..
  - export GTA3SC=$(readlink -f build/gta3sc)
  - lit test --verbose

