language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['libstdc++-8-dev', 'clang-6.0']
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=true -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cmake --build .
  - ctest . --verbose
