language: ruby
cache: bundler
rvm:
  - 2.4.1
branches:
  only:
    - gh-pages
install:
  - bundle install
script:
  - bundle exec jekyll build
before_deploy:
  - echo $GTA3SC_HOST_KEY >> $HOME/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_4b24469c5277_key -iv $encrypted_4b24469c5277_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avr --delete-after --delete-excluded --quiet $TRAVIS_BUILD_DIR/_site/ $GTA3SC_HOST_PATH
  on:
    branch: gh-pages
